# Generated by Django 4.2 on 2023-05-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=10)),
                ('stock_num', models.CharField(max_length=10)),
                ('stock_price', models.CharField(max_length=10)),
                ('stock_open', models.CharField(max_length=10)),
                ('stock_highest', models.CharField(max_length=10)),
                ('stock_lowest', models.CharField(max_length=10)),
                ('stock_date', models.CharField(max_length=10)),
                ('turnover', models.CharField(max_length=10)),
            ],
            options={
                'db_table': '2023',
            },
        ),
    ]
